# custom variables, available in the templates via {{ site.myvariable }}
title: "Jekyll Actions Demo"
email: ""
description: ""
baseurl: ""
url: ""

# Build settings
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: minima
plugins:
 - jekyll-feed